const { Pool } = require("pg");

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

async function getColumnType(tableName, columnName = "id") {
  const { rows } = await pool.query(
    `
      SELECT udt_name
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = $1
        AND column_name = $2
      LIMIT 1
    `,
    [tableName, columnName],
  );

  if (!rows[0]) {
    return null;
  }

  return rows[0].udt_name === "uuid" ? "uuid" : "integer";
}

async function constraintExists(tableName, constraintName) {
  const { rows } = await pool.query(
    `
      SELECT 1
      FROM information_schema.table_constraints
      WHERE table_schema = 'public'
        AND table_name = $1
        AND constraint_name = $2
      LIMIT 1
    `,
    [tableName, constraintName],
  );

  return Boolean(rows[0]);
}

function idDefinition(idType) {
  return idType === "uuid"
    ? "UUID PRIMARY KEY DEFAULT gen_random_uuid()"
    : "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
}

function refType(idType) {
  return idType === "uuid" ? "UUID" : "INTEGER";
}

function arrayType(idType) {
  return idType === "uuid" ? "UUID[]" : "INTEGER[]";
}

async function ensureColumn(tableName, columnDefinition) {
  await pool.query(
    `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS ${columnDefinition}`,
  );
}

async function ensureConstraint(tableName, constraintName, sql) {
  if (await constraintExists(tableName, constraintName)) {
    return;
  }

  await pool.query(sql);
}

const initDB = async () => {
  await pool.query("CREATE EXTENSION IF NOT EXISTS pgcrypto");

  const defaultIdType =
    (await getColumnType("members")) ||
    (await getColumnType("projects")) ||
    "uuid";
  const memberIdType = (await getColumnType("members")) || defaultIdType;
  const projectIdType = (await getColumnType("projects")) || defaultIdType;
  const taskIdType = (await getColumnType("tasks")) || defaultIdType;
  const clusterIdType = (await getColumnType("clusters")) || defaultIdType;
  const credentialClusterIdType =
    (await getColumnType("credential_clusters")) || defaultIdType;
  const knowledgeFolderIdType =
    (await getColumnType("knowledge_folders")) || defaultIdType;
  const calendarEventIdType =
    (await getColumnType("calendar_events")) || defaultIdType;

  await pool.query(`
    CREATE TABLE IF NOT EXISTS members (
      id ${idDefinition(memberIdType)},
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) UNIQUE NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('manager', 'developer')),
      birthday DATE,
      skills TEXT[],
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS projects (
      id ${idDefinition(projectIdType)},
      name VARCHAR(255) NOT NULL,
      client_name VARCHAR(255),
      description TEXT,
      status VARCHAR(30) DEFAULT 'active' CHECK (status IN ('active', 'on_hold', 'completed', 'archived')),
      start_date DATE,
      end_date DATE,
      custom_stages JSONB DEFAULT '["Todo","In Progress","In Review","Done","Deployed"]',
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS project_members (
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      PRIMARY KEY (project_id, member_id)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS clusters (
      id ${idDefinition(clusterIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      status VARCHAR(30) DEFAULT 'draft' CHECK (status IN ('draft','in_review','approved','needs_rework','completed')),
      rework_count INTEGER DEFAULT 0,
      target_date DATE,
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await ensureColumn("clusters", "description TEXT");
  await ensureColumn("clusters", "target_date DATE");
  await ensureColumn("clusters", `created_by ${refType(memberIdType)}`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS tasks (
      id ${idDefinition(taskIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      cluster_id ${refType(clusterIdType)} REFERENCES clusters(id) ON DELETE CASCADE,
      title VARCHAR(500) NOT NULL,
      description TEXT,
      assignee_id ${refType(memberIdType)} REFERENCES members(id),
      priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
      stage VARCHAR(100) DEFAULT 'Todo',
      due_date DATE,
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_comments (
      id ${idDefinition(defaultIdType)},
      task_id ${refType(taskIdType)} REFERENCES tasks(id) ON DELETE CASCADE,
      author_id ${refType(memberIdType)} REFERENCES members(id),
      content TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_activity (
      id ${idDefinition(defaultIdType)},
      task_id ${refType(taskIdType)} REFERENCES tasks(id) ON DELETE CASCADE,
      actor_id ${refType(memberIdType)} REFERENCES members(id),
      action VARCHAR(255),
      meta JSONB,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS cluster_reviews (
      id ${idDefinition(defaultIdType)},
      cluster_id ${refType(clusterIdType)} REFERENCES clusters(id) ON DELETE CASCADE,
      reviewer_id ${refType(memberIdType)} REFERENCES members(id),
      decision VARCHAR(20) CHECK (decision IN ('approved','needs_rework')),
      notes TEXT,
      rework_task_ids ${arrayType(taskIdType)},
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS credential_clusters (
      id ${idDefinition(credentialClusterIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      visibility VARCHAR(10) DEFAULT 'private' CHECK (visibility IN ('private','public')),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS credential_entries (
      id ${idDefinition(defaultIdType)},
      cluster_id ${refType(credentialClusterIdType)} REFERENCES credential_clusters(id) ON DELETE CASCADE,
      label VARCHAR(255) NOT NULL,
      value TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledge_folders (
      id ${idDefinition(knowledgeFolderIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      parent_id ${refType(knowledgeFolderIdType)} REFERENCES knowledge_folders(id),
      name VARCHAR(255) NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledge_files (
      id ${idDefinition(defaultIdType)},
      folder_id ${refType(knowledgeFolderIdType)} REFERENCES knowledge_folders(id) ON DELETE CASCADE,
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      name VARCHAR(500) NOT NULL,
      file_url TEXT NOT NULL,
      file_size INTEGER,
      mime_type VARCHAR(100),
      uploaded_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledge_notes (
      id ${idDefinition(defaultIdType)},
      folder_id ${refType(knowledgeFolderIdType)} REFERENCES knowledge_folders(id) ON DELETE CASCADE,
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      title VARCHAR(500) NOT NULL,
      content TEXT,
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS calendar_events (
      id ${idDefinition(calendarEventIdType)},
      title VARCHAR(500) NOT NULL,
      description TEXT,
      start_date TIMESTAMPTZ NOT NULL,
      end_date TIMESTAMPTZ NOT NULL,
      type VARCHAR(50) DEFAULT 'event' CHECK (type IN ('event', 'task', 'deadline', 'birthday')),
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await ensureColumn("calendar_events", "updated_at TIMESTAMPTZ DEFAULT NOW()");

  await pool.query(`
    CREATE TABLE IF NOT EXISTS calendar_attendees (
      event_id ${refType(calendarEventIdType)} REFERENCES calendar_events(id) ON DELETE CASCADE,
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      PRIMARY KEY (event_id, member_id)
    )
  `);

  await ensureColumn("calendar_attendees", "created_at TIMESTAMPTZ DEFAULT NOW()");
  await ensureConstraint(
    "calendar_attendees",
    "calendar_attendees_pkey",
    "ALTER TABLE calendar_attendees ADD CONSTRAINT calendar_attendees_pkey PRIMARY KEY (event_id, member_id)",
  );

  await pool.query(`
    CREATE TABLE IF NOT EXISTS notifications (
      id ${idDefinition(defaultIdType)},
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      message TEXT NOT NULL,
      read BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  console.log("Database schema ready");
};

initDB().catch(console.error);

module.exports = pool;
