const { Pool } = require("pg");

// Kept deliberately small: Supabase's session-mode pooler on this plan
// caps total simultaneous connections at 15 — shared across this local
// dev server, production, and anything else pointed at the same
// DATABASE_URL. Leaving max low here means one crash-restart loop can't
// eat the whole budget on its own.
//
// Unused connections are kept for 5 minutes by default
// (DB_POOL_IDLE_TIMEOUT_MS). With the old 30 s, a quiet moment closed every
// connection and the next request had to open a new one through the pooler
// (about 200 ms extra).
const DEFAULT_IDLE_TIMEOUT_MS = 300000;

function readIdleTimeout() {
  const value = Number.parseInt(process.env.DB_POOL_IDLE_TIMEOUT_MS, 10);
  return Number.isInteger(value) && value >= 0 ? value : DEFAULT_IDLE_TIMEOUT_MS;
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DB_SSL === "true" ? { rejectUnauthorized: false } : false,
  max: 5,
  idleTimeoutMillis: readIdleTimeout(),
  connectionTimeoutMillis: 5000,
});

pool.on("error", (err) => {
  // A background/idle client erroring out (e.g. the pooler dropping a
  // connection) would otherwise crash the whole process — log it and
  // let the pool recover instead.
  console.error("[db] Unexpected pg pool error:", err.message);
});

// Release every connection back to Supabase on shutdown — including
// nodemon's restart signal — instead of leaving them dangling until the
// pooler's own idle-timeout eventually reaps them.
async function shutdownPool(signal) {
  try {
    await pool.end();
    console.log(`[db] Pool closed cleanly on ${signal}.`);
  } catch (err) {
    console.error(`[db] Error closing pool on ${signal}:`, err.message);
  } finally {
    process.exit(0);
  }
}
if (!process.env.VERCEL) {
  process.on("SIGINT", () => shutdownPool("SIGINT"));
  process.on("SIGTERM", () => shutdownPool("SIGTERM"));
  process.once("SIGUSR2", () => shutdownPool("SIGUSR2"));
}

// ---------------------------------------------------------------------
// Migration tracking — every one-time backfill/data-migration below is
// gated on this table so it runs exactly once, ever, instead of being
// replayed (with a full-table scan) on every single server boot.
// ---------------------------------------------------------------------
async function ensureMigrationsTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS schema_migrations (
      name VARCHAR(255) PRIMARY KEY,
      run_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);
}

async function hasMigrationRun(name) {
  const { rows } = await pool.query(
    `SELECT 1 FROM schema_migrations WHERE name = $1`,
    [name],
  );
  return rows.length > 0;
}

async function markMigrationRun(name) {
  await pool.query(
    `INSERT INTO schema_migrations (name, run_at) VALUES ($1, NOW())
     ON CONFLICT (name) DO NOTHING`,
    [name],
  );
}

// Run a one-time migration exactly once, tracked by name.
async function runOnce(name, fn) {
  if (await hasMigrationRun(name)) {
    return;
  }
  await fn();
  await markMigrationRun(name);
}

async function getColumnType(tableName, columnName = "id") {
  const { rows } = await pool.query(
    `
      SELECT udt_name
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = $1
        AND column_name = $2
      LIMIT 1
    `,
    [tableName, columnName],
  );

  if (!rows[0]) {
    return null;
  }

  return rows[0].udt_name === "uuid" ? "uuid" : "integer";
}

async function constraintExists(tableName, constraintName) {
  const { rows } = await pool.query(
    `
      SELECT 1
      FROM information_schema.table_constraints
      WHERE table_schema = 'public'
        AND table_name = $1
        AND constraint_name = $2
      LIMIT 1
    `,
    [tableName, constraintName],
  );

  return Boolean(rows[0]);
}

function idDefinition(idType) {
  return idType === "uuid"
    ? "UUID PRIMARY KEY DEFAULT gen_random_uuid()"
    : "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
}

function refType(idType) {
  return idType === "uuid" ? "UUID" : "INTEGER";
}

function arrayType(idType) {
  return idType === "uuid" ? "UUID[]" : "INTEGER[]";
}

async function ensureColumn(tableName, columnDefinition) {
  await pool.query(
    `ALTER TABLE ${tableName} ADD COLUMN IF NOT EXISTS ${columnDefinition}`,
  );
}

async function ensureConstraint(tableName, constraintName, sql) {
  if (await constraintExists(tableName, constraintName)) {
    return;
  }

  await pool.query(sql);
}

const initDB = async () => {
  await pool.query("CREATE EXTENSION IF NOT EXISTS pgcrypto");
  await ensureMigrationsTable();

  // id-type detection — still runs each boot (cheap, indexed lookups),
  // but only until every table has a resolvable id type; once
  // getColumnType stops returning null for these, this is effectively
  // free (single-row indexed reads against information_schema).
  const defaultIdType =
    (await getColumnType("members")) ||
    (await getColumnType("projects")) ||
    "uuid";
  const memberIdType = (await getColumnType("members")) || defaultIdType;
  const projectIdType = (await getColumnType("projects")) || defaultIdType;
  const taskIdType = (await getColumnType("tasks")) || defaultIdType;
  const clusterIdType = (await getColumnType("clusters")) || defaultIdType;
  const credentialClusterIdType =
    (await getColumnType("credential_clusters")) || defaultIdType;
  const knowledgeFolderIdType =
    (await getColumnType("knowledge_folders")) || defaultIdType;
  const calendarEventIdType =
    (await getColumnType("calendar_events")) || defaultIdType;

  await pool.query(`
    CREATE TABLE IF NOT EXISTS members (
      id ${idDefinition(memberIdType)},
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) UNIQUE NOT NULL,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('manager', 'member')),
      birthday DATE,
      skills TEXT[],
      active BOOLEAN DEFAULT true,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  // Profile columns — added progressively, safe to re-run
  await ensureColumn("members", "phone VARCHAR(50)");
  await ensureColumn("members", "location VARCHAR(255)");
  await ensureColumn("members", "bio TEXT");
  await ensureColumn("members", "avatar_url TEXT");

  await pool.query(`
  CREATE TABLE IF NOT EXISTS refresh_tokens (
    id ${idDefinition(defaultIdType)},
    member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
    session_id UUID,
    jti TEXT UNIQUE NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    replaced_by TEXT,
    revoke_reason TEXT,
    user_agent TEXT,
    ip_address TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )
`);

  await ensureColumn("refresh_tokens", "session_id UUID");
  // Used for "first seen" / "last active" in the Active sessions list.
  // Already in the CREATE TABLE above; this only covers a table that was
  // created before the column was there. No-op otherwise.
  await ensureColumn("refresh_tokens", "created_at TIMESTAMPTZ DEFAULT NOW()");

  await pool.query(`
    CREATE TABLE IF NOT EXISTS projects (
      id ${idDefinition(projectIdType)},
      name VARCHAR(255) NOT NULL,
      client_name VARCHAR(255),
      description TEXT,
      status VARCHAR(30) DEFAULT 'active' CHECK (status IN ('active', 'on_hold', 'completed', 'archived')),
      start_date DATE,
      end_date DATE,
      custom_stages JSONB DEFAULT '["Todo","In Progress","In Review","Done"]',
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS project_members (
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      PRIMARY KEY (project_id, member_id)
    )
  `);

  // Drag-and-drop project ordering. Backfill gives every existing
  // project a stable initial position (newest first, matching the old
  // created_at DESC sort) so the very first render after this migration
  // looks identical to before — nothing visibly jumps around.
  // Tracked in schema_migrations so this full-table window-function
  // scan runs exactly once, not on every boot.
  await ensureColumn("projects", "sort_order INTEGER");
  await runOnce("backfill_projects_sort_order", async () => {
    await pool.query(`
      UPDATE projects SET sort_order = ranked.rn
      FROM (
        SELECT id, ROW_NUMBER() OVER (ORDER BY created_at DESC) AS rn
        FROM projects
      ) ranked
      WHERE projects.id = ranked.id AND projects.sort_order IS NULL
    `);
  });

  // Optional external links shown as buttons on the project card/details page.
  // Nullable and idempotent (ADD COLUMN IF NOT EXISTS), so safe on every boot
  // and on fresh databases.
  await ensureColumn("projects", "milanote_url TEXT");
  await ensureColumn("projects", "docs_url TEXT");

  await pool.query(`
    CREATE TABLE IF NOT EXISTS clusters (
      id ${idDefinition(clusterIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      description TEXT,
      status VARCHAR(30) DEFAULT 'draft' CHECK (status IN ('draft','in_review','approved','needs_rework','completed')),
      rework_count INTEGER DEFAULT 0,
      target_date DATE,
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await ensureColumn("clusters", "description TEXT");
  await ensureColumn("clusters", "target_date DATE");
  await ensureColumn("clusters", `created_by ${refType(memberIdType)}`);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS tasks (
      id ${idDefinition(taskIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      cluster_id ${refType(clusterIdType)} REFERENCES clusters(id) ON DELETE CASCADE,
      title VARCHAR(500) NOT NULL,
      description TEXT,
      assignee_id ${refType(memberIdType)} REFERENCES members(id),
      priority VARCHAR(20) DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
      stage VARCHAR(100) DEFAULT 'Todo',
      due_date DATE,
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await ensureColumn(
    "tasks",
    `parent_task_id ${refType(taskIdType)} REFERENCES tasks(id) ON DELETE CASCADE`,
  );

  // Multi-assignee support: a task/subtask can now have several people
  // assigned. tasks.assignee_id is kept around (unused going forward) so
  // nothing that reads it directly breaks; this table is the source of
  // truth from here on.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_assignees (
      task_id ${refType(taskIdType)} REFERENCES tasks(id) ON DELETE CASCADE,
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      PRIMARY KEY (task_id, member_id)
    )
  `);

  // One-time backfill: carry every existing single-assignee task over into
  // the new table. Tracked so it runs once instead of scanning `tasks`
  // (with an ON CONFLICT no-op per row) on every boot.
  await runOnce("backfill_task_assignees", async () => {
    await pool.query(`
      INSERT INTO task_assignees (task_id, member_id)
      SELECT id, assignee_id FROM tasks WHERE assignee_id IS NOT NULL
      ON CONFLICT DO NOTHING
    `);
  });

  // Used by every task update (time tracking + rework counter) but never
  // created here, so a fresh database couldn't update tasks. No-op on
  // databases that already have them.
  await ensureColumn("tasks", "time_taken INTEGER");
  await ensureColumn("tasks", "rework_count INTEGER DEFAULT 0");

  // Drag-and-drop task ordering within a board column (and moving a card
  // between columns). Backfill preserves the current created_at DESC
  // order per (project, stage) column so nothing visibly reshuffles the
  // first time this runs. Tracked — this is a per-partition window-
  // function scan over all tasks, too expensive to repeat every boot.
  await ensureColumn("tasks", "sort_order INTEGER");
  await runOnce("backfill_tasks_sort_order", async () => {
    await pool.query(`
      UPDATE tasks SET sort_order = ranked.rn
      FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY project_id, stage ORDER BY created_at DESC) AS rn
        FROM tasks
      ) ranked
      WHERE tasks.id = ranked.id AND tasks.sort_order IS NULL
    `);
  });

  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_comments (
      id ${idDefinition(defaultIdType)},
      task_id ${refType(taskIdType)} REFERENCES tasks(id) ON DELETE CASCADE,
      author_id ${refType(memberIdType)} REFERENCES members(id),
      content TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_activity (
      id ${idDefinition(defaultIdType)},
      task_id ${refType(taskIdType)} REFERENCES tasks(id) ON DELETE CASCADE,
      actor_id ${refType(memberIdType)} REFERENCES members(id),
      action VARCHAR(255),
      meta JSONB,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS cluster_reviews (
      id ${idDefinition(defaultIdType)},
      cluster_id ${refType(clusterIdType)} REFERENCES clusters(id) ON DELETE CASCADE,
      reviewer_id ${refType(memberIdType)} REFERENCES members(id),
      decision VARCHAR(20) CHECK (decision IN ('approved','needs_rework')),
      notes TEXT,
      rework_task_ids ${arrayType(taskIdType)},
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS credential_clusters (
      id ${idDefinition(credentialClusterIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      visibility VARCHAR(10) DEFAULT 'private' CHECK (visibility IN ('private','public')),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS credential_entries (
      id ${idDefinition(defaultIdType)},
      cluster_id ${refType(credentialClusterIdType)} REFERENCES credential_clusters(id) ON DELETE CASCADE,
      label VARCHAR(255) NOT NULL,
      value TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledge_folders (
      id ${idDefinition(knowledgeFolderIdType)},
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      parent_id ${refType(knowledgeFolderIdType)} REFERENCES knowledge_folders(id),
      name VARCHAR(255) NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledge_files (
      id ${idDefinition(defaultIdType)},
      folder_id ${refType(knowledgeFolderIdType)} REFERENCES knowledge_folders(id) ON DELETE CASCADE,
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      name VARCHAR(500) NOT NULL,
      file_url TEXT NOT NULL,
      file_size INTEGER,
      mime_type VARCHAR(100),
      uploaded_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledge_notes (
      id ${idDefinition(defaultIdType)},
      folder_id ${refType(knowledgeFolderIdType)} REFERENCES knowledge_folders(id) ON DELETE CASCADE,
      project_id ${refType(projectIdType)} REFERENCES projects(id) ON DELETE CASCADE,
      title VARCHAR(500) NOT NULL,
      content TEXT,
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS calendar_events (
      id ${idDefinition(calendarEventIdType)},
      title VARCHAR(500) NOT NULL,
      description TEXT,
      start_date TIMESTAMPTZ NOT NULL,
      end_date TIMESTAMPTZ NOT NULL,
      type VARCHAR(50) DEFAULT 'event' CHECK (type IN ('event', 'task', 'deadline', 'birthday')),
      created_by ${refType(memberIdType)} REFERENCES members(id),
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await ensureColumn("calendar_events", "updated_at TIMESTAMPTZ DEFAULT NOW()");

  await pool.query(`
    CREATE TABLE IF NOT EXISTS calendar_attendees (
      event_id ${refType(calendarEventIdType)} REFERENCES calendar_events(id) ON DELETE CASCADE,
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      PRIMARY KEY (event_id, member_id)
    )
  `);

  await ensureColumn(
    "calendar_attendees",
    "created_at TIMESTAMPTZ DEFAULT NOW()",
  );
  await ensureConstraint(
    "calendar_attendees",
    "calendar_attendees_pkey",
    "ALTER TABLE calendar_attendees ADD CONSTRAINT calendar_attendees_pkey PRIMARY KEY (event_id, member_id)",
  );

  await pool.query(`
    CREATE TABLE IF NOT EXISTS notifications (
      id ${idDefinition(defaultIdType)},
      member_id ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
      message TEXT NOT NULL,
      type VARCHAR(50) DEFAULT 'general',
      title VARCHAR(255),
      body TEXT,
      related_entity_id TEXT,
      related_entity_type VARCHAR(50),
      metadata JSONB DEFAULT '{}'::jsonb,
      dedupe_key TEXT,
      read BOOLEAN DEFAULT false,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await ensureColumn("notifications", "type VARCHAR(50) DEFAULT 'general'");
  await ensureColumn("notifications", "title VARCHAR(255)");
  await ensureColumn("notifications", "body TEXT");
  await ensureColumn("notifications", "related_entity_id TEXT");
  await ensureColumn("notifications", "related_entity_type VARCHAR(50)");
  await ensureColumn("notifications", "metadata JSONB DEFAULT '{}'::jsonb");
  await ensureColumn("notifications", "dedupe_key TEXT");

  await pool.query(`
  CREATE TABLE IF NOT EXISTS push_subscriptions (
    id         ${idDefinition(defaultIdType)},
    member_id  ${refType(memberIdType)} REFERENCES members(id) ON DELETE CASCADE,
    endpoint   TEXT UNIQUE NOT NULL,
    p256dh     TEXT NOT NULL,
    auth       TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
  )
`);

  // The session (browser tab) that saved the subscription, so it can be
  // removed when that session is revoked. Nullable: rows saved before this
  // column existed have none.
  await ensureColumn("push_subscriptions", "session_id UUID");

  await pool.query(`
    CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_member_dedupe
    ON notifications (member_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_notifications_member_created
    ON notifications (member_id, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_push_subscriptions_member
    ON push_subscriptions (member_id)
  `);

  // One-time migration: remove 'Deployed' from existing projects'
  // custom_stages. Tracked — the untracked version re-scanned every
  // project row's JSONB array on every single boot forever.
  await runOnce("remove_deployed_stage", async () => {
    await pool.query(`
      UPDATE projects
      SET custom_stages = (
        SELECT jsonb_agg(stage)
        FROM jsonb_array_elements_text(custom_stages) AS stage
        WHERE stage != 'Deployed'
      )
      WHERE custom_stages @> '["Deployed"]'::jsonb
    `);
  });

  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_refresh_tokens_member_id
    ON refresh_tokens (member_id)
  `);
  await pool.query(`
  CREATE INDEX IF NOT EXISTS idx_refresh_tokens_session_id
  ON refresh_tokens (session_id)
`);

  await pool.query(`
  CREATE INDEX IF NOT EXISTS idx_refresh_tokens_member_session
  ON refresh_tokens (member_id, session_id)
`);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_refresh_tokens_jti
    ON refresh_tokens (jti)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at)
  `);

  // Sessions: the Active sessions list, the session check in the auth
  // middleware, and the daily cleanup of old rows. A live session has
  // exactly one row that is not revoked, so the two "revoked_at IS NULL"
  // indexes stay tiny however many old rows a session leaves behind.
  // Additive and idempotent.
  const sessionIndexes = [
    // auth middleware: is this session still active?
    ["idx_refresh_tokens_active_session", "refresh_tokens (session_id) WHERE revoked_at IS NULL"],
    // sessions list, "sign out other devices", log out everywhere
    ["idx_refresh_tokens_member_active", "refresh_tokens (member_id) WHERE revoked_at IS NULL"],
    // cleanup: rows revoked longer ago than the retention window
    // (rows expired that long ago use idx_refresh_tokens_expires_at)
    ["idx_refresh_tokens_revoked_at", "refresh_tokens (revoked_at) WHERE revoked_at IS NOT NULL"],
    // removing a revoked session's push subscriptions
    ["idx_push_subscriptions_session", "push_subscriptions (session_id) WHERE session_id IS NOT NULL"],
  ];
  for (const [name, definition] of sessionIndexes) {
    await pool.query(`CREATE INDEX IF NOT EXISTS ${name} ON ${definition}`);
  }
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_tasks_project_id
    ON tasks (project_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_tasks_project_sort
    ON tasks (project_id, sort_order, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_tasks_due_date
    ON tasks (due_date)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_task_assignees_member_id
    ON task_assignees (member_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_task_comments_task_created
    ON task_comments (task_id, created_at)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_task_activity_task_created
    ON task_activity (task_id, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_calendar_attendees_member_id
    ON calendar_attendees (member_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_projects_sort_order
    ON projects (sort_order, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_project_members_member
    ON project_members (member_id)
  `);

  // Previously missing FK-lookup indexes — added to cover common
  // project-scoped queries against these tables.
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_knowledge_files_project_id
    ON knowledge_files (project_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_knowledge_notes_project_id
    ON knowledge_notes (project_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_credential_entries_cluster_id
    ON credential_entries (cluster_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_cluster_reviews_cluster_id
    ON cluster_reviews (cluster_id)
  `);

  // Hot lookups that were doing sequential scans: sub task lists and
  // parent stage/due-date recomputes (parent_task_id), cluster task
  // lists, the In Review queue, per-project clusters / credentials /
  // knowledge folders, folder file lists, and the unread badge count.
  // Additive and idempotent.
  const extraIndexes = [
    ["idx_tasks_parent_task_id", "tasks (parent_task_id)"],
    ["idx_tasks_cluster_id", "tasks (cluster_id)"],
    ["idx_tasks_stage_updated", "tasks (stage, updated_at DESC)"],
    ["idx_clusters_project_id", "clusters (project_id)"],
    ["idx_credential_clusters_project_id", "credential_clusters (project_id)"],
    ["idx_knowledge_folders_project_id", "knowledge_folders (project_id)"],
    ["idx_knowledge_files_folder_id", "knowledge_files (folder_id)"],
    ["idx_notifications_member_unread", "notifications (member_id) WHERE read = false"],
    ["idx_calendar_events_start_date", "calendar_events (start_date)"],
  ];
  for (const [name, definition] of extraIndexes) {
    await pool.query(`CREATE INDEX IF NOT EXISTS ${name} ON ${definition}`);
  }

  // Task requests: members ask for a task, managers review them on the
  // "Requested Tasks" page and delete them once handled.
  await pool.query(`
    CREATE TABLE IF NOT EXISTS task_requests (
      id ${idDefinition(defaultIdType)},
      title VARCHAR(500) NOT NULL,
      project_name VARCHAR(255) NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      due_date DATE,
      requested_by ${refType(memberIdType)} NOT NULL REFERENCES members(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS task_requests_created_at_idx
    ON task_requests (created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_task_requests_requested_by
    ON task_requests (requested_by)
  `);

  // -------------------------------------------------------------------
  // Dashboard activity log.
  //
  // One row per event the dashboard "Activity" chart counts. Rows are
  // written by database triggers (below), so every code path that creates
  // a task / comment / project or moves a task between stages is captured
  // without touching the services. entity_id is TEXT so it works for both
  // integer and uuid ids.
  //
  // event_type values:
  //   task_created, task_completed, task_in_progress, task_in_review,
  //   task_rework, comment_added,
  //   project_created, project_updated, project_archived
  // -------------------------------------------------------------------
  await pool.query(`
    CREATE TABLE IF NOT EXISTS activity_log (
      id BIGSERIAL PRIMARY KEY,
      event_type TEXT NOT NULL,
      entity_type TEXT NOT NULL,
      entity_id TEXT,
      meta JSONB DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_activity_log_created_type
    ON activity_log (created_at, event_type)
  `);

  // One-time backfill of the last 60 days so the chart is not empty on
  // day one. Created / comments / projects are exact. "Completed" is an
  // approximation (tasks currently Done, dated by updated_at), because
  // the old schema never recorded when a task was completed.
  await runOnce("backfill_activity_log_v1", async () => {
    await pool.query(`
      INSERT INTO activity_log (event_type, entity_type, entity_id, created_at)
      SELECT 'task_created', 'task', id::text, created_at
      FROM tasks WHERE created_at >= NOW() - INTERVAL '60 days'
    `);
    await pool.query(`
      INSERT INTO activity_log (event_type, entity_type, entity_id, created_at)
      SELECT 'comment_added', 'task', task_id::text, created_at
      FROM task_comments WHERE created_at >= NOW() - INTERVAL '60 days'
    `);
    await pool.query(`
      INSERT INTO activity_log (event_type, entity_type, entity_id, created_at)
      SELECT 'project_created', 'project', id::text, created_at
      FROM projects WHERE created_at >= NOW() - INTERVAL '60 days'
    `);
    await pool.query(`
      INSERT INTO activity_log (event_type, entity_type, entity_id, created_at)
      SELECT 'task_completed', 'task', id::text, updated_at
      FROM tasks
      WHERE stage = 'Done' AND updated_at >= NOW() - INTERVAL '60 days'
    `);
  });

  // Triggers that keep activity_log up to date. Versioned name: bump the
  // suffix if you ever change the functions below.
  await runOnce("activity_log_triggers_v1", async () => {
    await pool.query(`
      CREATE OR REPLACE FUNCTION log_task_activity() RETURNS trigger AS $$
      DECLARE
        v_event TEXT;
      BEGIN
        IF TG_OP = 'INSERT' THEN
          INSERT INTO activity_log (event_type, entity_type, entity_id, meta)
          VALUES ('task_created', 'task', NEW.id::text,
                  jsonb_build_object('project_id', NEW.project_id::text));
          RETURN NEW;
        END IF;

        IF NEW.stage IS DISTINCT FROM OLD.stage THEN
          v_event := CASE NEW.stage
            WHEN 'Done' THEN 'task_completed'
            WHEN 'In Progress' THEN 'task_in_progress'
            WHEN 'In Review' THEN 'task_in_review'
            ELSE NULL
          END;
          IF v_event IS NOT NULL THEN
            INSERT INTO activity_log (event_type, entity_type, entity_id, meta)
            VALUES (v_event, 'task', NEW.id::text,
                    jsonb_build_object('from', OLD.stage, 'to', NEW.stage));
          END IF;
        END IF;

        IF COALESCE(NEW.rework_count, 0) > COALESCE(OLD.rework_count, 0) THEN
          INSERT INTO activity_log (event_type, entity_type, entity_id)
          VALUES ('task_rework', 'task', NEW.id::text);
        END IF;

        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    `);
    await pool.query(`DROP TRIGGER IF EXISTS trg_task_activity ON tasks`);
    await pool.query(`
      CREATE TRIGGER trg_task_activity
      AFTER INSERT OR UPDATE OF stage, rework_count ON tasks
      FOR EACH ROW EXECUTE FUNCTION log_task_activity()
    `);

    await pool.query(`
      CREATE OR REPLACE FUNCTION log_comment_activity() RETURNS trigger AS $$
      BEGIN
        INSERT INTO activity_log (event_type, entity_type, entity_id)
        VALUES ('comment_added', 'task', NEW.task_id::text);
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    `);
    await pool.query(`DROP TRIGGER IF EXISTS trg_comment_activity ON task_comments`);
    await pool.query(`
      CREATE TRIGGER trg_comment_activity
      AFTER INSERT ON task_comments
      FOR EACH ROW EXECUTE FUNCTION log_comment_activity()
    `);

    // Projects: created, or meaningfully edited (drag-reorder via
    // sort_order is deliberately NOT counted).
    await pool.query(`
      CREATE OR REPLACE FUNCTION log_project_activity() RETURNS trigger AS $$
      BEGIN
        IF TG_OP = 'INSERT' THEN
          INSERT INTO activity_log (event_type, entity_type, entity_id)
          VALUES ('project_created', 'project', NEW.id::text);
          RETURN NEW;
        END IF;

        IF NEW.status = 'archived' AND OLD.status IS DISTINCT FROM 'archived' THEN
          INSERT INTO activity_log (event_type, entity_type, entity_id)
          VALUES ('project_archived', 'project', NEW.id::text);
        ELSIF NEW.name IS DISTINCT FROM OLD.name
           OR NEW.client_name IS DISTINCT FROM OLD.client_name
           OR NEW.description IS DISTINCT FROM OLD.description
           OR NEW.status IS DISTINCT FROM OLD.status
           OR NEW.start_date IS DISTINCT FROM OLD.start_date
           OR NEW.end_date IS DISTINCT FROM OLD.end_date
           OR NEW.milanote_url IS DISTINCT FROM OLD.milanote_url
           OR NEW.docs_url IS DISTINCT FROM OLD.docs_url THEN
          INSERT INTO activity_log (event_type, entity_type, entity_id)
          VALUES ('project_updated', 'project', NEW.id::text);
        END IF;

        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    `);
    await pool.query(`DROP TRIGGER IF EXISTS trg_project_activity ON projects`);
    await pool.query(`
      CREATE TRIGGER trg_project_activity
      AFTER INSERT OR UPDATE ON projects
      FOR EACH ROW EXECUTE FUNCTION log_project_activity()
    `);
  });

  console.log("Database schema ready");
};

// ---------------------------------------------------------------------
// activity_log retention. The dashboard chart only reads the last 14 days
// and the backfill covers 60, so 90 days is a safe default. Override with
// ACTIVITY_LOG_RETENTION_DAYS (kept at 15 or more so the 14-day chart
// never loses data).
// ---------------------------------------------------------------------
const ACTIVITY_RETENTION_DAYS = Math.max(
  15,
  Number.parseInt(process.env.ACTIVITY_LOG_RETENTION_DAYS, 10) || 90,
);
const CLEANUP_INTERVAL_MS = 24 * 60 * 60 * 1000;

async function cleanupActivityLog() {
  try {
    const { rowCount } = await pool.query(
      `DELETE FROM activity_log
       WHERE created_at < NOW() - make_interval(days => $1)`,
      [ACTIVITY_RETENTION_DAYS],
    );
    if (rowCount) {
      console.log(
        `[db] activity_log cleanup: removed ${rowCount} rows older than ${ACTIVITY_RETENTION_DAYS} days.`,
      );
    }
  } catch (err) {
    // Never let a cleanup failure affect the app.
    console.error("[db] activity_log cleanup failed:", err.message);
  }
}

// The app always prepares the schema when this module is first loaded.
// One-off scripts in server/scripts/ that only need the pool set
// DB_SKIP_INIT=true before requiring it, so they send nothing but their
// own statements.
if (process.env.DB_SKIP_INIT !== "true") {
  initDB()
    .then(() => {
      // Once at boot, then daily on a long-running server.
      cleanupActivityLog();
      if (!process.env.VERCEL) {
        // unref() so this timer never keeps the process alive on shutdown.
        setInterval(cleanupActivityLog, CLEANUP_INTERVAL_MS).unref();
      }
    })
    .catch(console.error);
}

// Exposed so a cron route or script can trigger the cleanup.
pool.cleanupActivityLog = cleanupActivityLog;

module.exports = pool;